name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
  id-token: write
  pages: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          pip install faker
          pip install pytest
    
      - name: Create CSV file
        run: python generate.py
      
      - name: Create JSON file
        run: python csvtojson.py
      
      - name: Run unit tests
        run: |
          pytest Test2.py
          pytest test.py
        continue-on-error: false
        
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test_results
          
      - name: Copy to dist
        run: |
          mkdir -p dist
          cp index.html dist/index.html
          cp data.json dist/data.json
          cp script.js dist/script.js
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Deploy to GitHub Pages
        if: always() && success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

        
